services:
  - type: web
    name: telegram-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    build:
      pythonVersion: 3.11.8
